name: clx

services:
    nats:
        image: nats:latest
        ports:
            - "4222:4222"
            - "6222:6222"
            - "8222:8222"
        command: "-c /etc/nats/nats-server.conf"
        volumes:
            - ./nats-server.conf:/etc/nats/nats-server.conf
        networks:
            - app-network

    notebook-processor:
        build:
            context: ./notebook-processor
        depends_on:
            nats:
                condition: service_started
        networks:
            - app-network
        develop:
            watch:
                -   action: sync+restart
                    path: ./notebook-processor
                    target: /app
        environment:
            - NATS_URL=nats://nats:4222
            - LOG_LEVEL=INFO
        deploy:
            mode: replicated
            replicas: 1

    drawio-converter:
        build:
            context: ./drawio-converter
        depends_on:
            nats:
                condition: service_started
        environment:
            - NATS_URL=nats://nats:4222
            - LOG_LEVEL=INFO
            - DISPLAY=:99
        networks:
            - app-network
        init: true
        develop:
            watch:
                -   action: sync+restart
                    path: ./drawio-converter
                    target: /app
        deploy:
            mode: replicated
            replicas: 1

    plantuml-converter:
        build:
            context: ./plantuml-converter
        depends_on:
            nats:
                condition: service_started
        environment:
            - NATS_URL=nats://nats:4222
            - LOG_LEVEL=INFO
        networks:
            - app-network
        develop:
            watch:
                -   action: sync+restart
                    path: ./plantuml-converter
                    target: /app
        deploy:
            mode: replicated
            replicas: 1

networks:
    app-network:
        driver: bridge